### ISSUE TITLE
Custom @contextmenu handler

### ISSUE THREAD

**Issue by fsproru** [bhuh12/vue-router-tab#79]
**Is your feature request related to a problem? Please describe.**
Looks like `<router-tab>` component eats all @contextmenu events. We usually pop up a native system menu as opposed to a menu in Javascript.

**Describe the solution you'd like**
It would be great if we can specify our own handler for @contextmenu line this

```
<router-tab
  @contextmenu="ownOwnHandler"
/>
```

**Describe alternatives you've considered**
Our best bet is to try to style the Javascript menu popping up to be as close as possible to the system menu. That being said, it won't be exactly the same on all platforms (Windows, Linux, and macOS)

**Comment by bhuh12** [comment]
Do you mean to use the system native menu instead of RouterTab's built-in menu?

![image](https://user-images.githubusercontent.com/9862292/94988852-d2898200-05a2-11eb-9d75-00184640ef77.png)

You can disabled RouterTab's built-in menu, and listen to native contextmenu events like this

``` html
<router-tab :contextmenu="false" @contextmenu.native="context" />
```

https://bhuh12.github.io/vue-router-tab/guide/custom/contextmenu.html

**Comment by fsproru** [comment]
Oh nice, it's `.native` part I was missing. Might be worth adding it to the documentation. Thank you.
